### ISSUE TITLE
Segmentation fault when using -Q4 (but not -Q7)

### ISSUE THREAD

**Issue by pvanheus** [ogotoh/spaln#10]
Hi there

I have put some data that demonstrates this problem here:

https://www.dropbox.com/sh/p8l0oepc2ihiaeb/AADWhzcgpb5E_Tfg266yk3kFa?dl=0

the command:

`spaln -Q4 -dhard_masked_seabass_genome fish_proteins_0.fasta`

results in a core dump on this data, with the last output before the segmentation fault being:

```
YP_003058361.1	NW_017365130.1 	  33.33	     17	      4	      0	    454	    459	  19552	  19568	   26.6	     85	    5.7	   0.00	  15.90  0 0  0 1 GT.AG
YP_003058361.1	NW_017365130.1 	   0.00	      6	      1	      1	    460	    460	  19644	  19649	   30.5	     75	   23.7	  18.60	  15.90  0 0  0 0 GT.AG
@ NW_017365130.1  + ( 10127 19649 ) YP_003058361.1 460 ( 1 460 ) S: 1454.2 =: 59.5 C: 35.6 T#: 173 T-: 4 B#: 0 B-: 0 X: 2 Pam: 0
Segmentation fault (core dumped)
```

The core dump happens at https://github.com/ogotoh/spaln/blob/master/src/aln.h#L119 when the pointer that `simmtx->mtx[*as]` points to (as part of `simmtx->mtx[*as][*bs]`) points to inaccessible memory.

**Comment by ogotoh** [comment]
In Version.2.3.3, this problem has been fixed.

The value for ‘NEVSEL’ defined in cmn.h has been halved. This prevent underflow when two NEVSEL-valued variables are added, which can happen in the ‘Hirschberg’ algorithm implemented in fwd2b1.c, fwd2h1.c, and fwd2s1.h. The underflowed score value eventually led to the core dump.

However, I still recommend to use –Q5~7 rather than –Q4, as –Q4 spend much more computational resource than –Q5~7.
