### ISSUE TITLE
What does the output mean by using spaln -O1 option

### ISSUE THREAD

**Issue by ljl000** [ogotoh/spaln#21]
Hi ogotoh,
 Recently, I used spaln to align aa  sequence to DNA sequence by using the parameter -O1.I don't understand about the  output "Score = 4091.0 (1174.1), 40.0 (=), 122.0 (#), 8.0 (g), 12.0 (u), (22.99 %)"means. Would you please help me about what does these numbers mean? Thanks a lot!
<img width="839" alt="屏幕快照 2019-08-27 下午5 06 08" src="https://user-images.githubusercontent.com/43433383/63757673-195f6f80-c8ed-11e9-9dbd-2bc269c2af6d.png">

**Comment by ogotoh** [comment]
I wonder your alignment was not successful because the two score values differ too much. Please refer to my comments in issue #19. Or you are trying intrinsically difficult alignment.

The first line indicates parameters used for alignment:
PAM: PAM level of Dayhoff’s style amino-acid substitution matrix. (by default spaln uses JTT matrix).
BIAS: If != 0, this value is added to the above substitution matrix. Adjustable with –yb_N_ option.
u: Gap extension penalty.
v: Gap open penalty.
The second line:
Score = _Row_ (_Modified_): alignment scores. Modified score takes account the number of inferred exons. Otherwise, intron-less processed pseudogenes might give better row score than the true gene.
_M_ (=): Number of identical residues between the query and (translated) genomic sequence.
_N_ (#): Number of mismatched residues between the query and (translated) genomic sequence.
_G_ (g): Number of gaps in the alignment after splicing.
_U_ (u) Number of unpaired (either being a space) residues in the alignment after splicing.
(_P_ %) Percent of identically matched sites in the alignment = 100*_M_/(_M_+_N_+_G_).
The third line:
A delineator indicating that the real alignment starts after this line.

**Comment by ljl000** [comment]
Thanks very much about your comment,  I also have another question.  Can I just treat the (=)number as the tblastn output Identities&Positives number or just the Indentities number between query and the translated genomic sequence?

**Comment by ogotoh** [comment]
I don’t very well understand your question. If you require a change in output format, it should be considered carefully, because the side effects of such changes cannot be easily anticipated. Although the number of positive matches is not immediately available, the number of identical matches is shown in _M_. So, you may prepare an awk (or any other) filter to alter the output format as you like. Alternatively, you may directory edit the source code, sqpr.c line 2267-2273, and then recompile spaln.

________________________________
差出人: ljl000 <notifications@github.com>
送信日時: 2019年8月29日 17:51
宛先: ogotoh/spaln <spaln@noreply.github.com>
CC: 後藤修 <o.gotoh@aist.go.jp>; Comment <comment@noreply.github.com>
件名: Re: [ogotoh/spaln] What does the output mean by using spaln -O1 option (#21)


Thanks very much about your comment, I also have another question. Can I just treat the (=)number as the tblastn output Identities&Positives number or just the Indentities number between query and the translated genomic sequence?

**Comment by ljl000** [comment]
Thank you very much. I have sorted it out.
