### ISSUE TITLE
Understanding -Q options (missing mappings)

### ISSUE THREAD

**Issue by marchoeppner** [ogotoh/spaln#35]
Hi,

I am trying to understand the difference between -Q4, -Q5, -Q6 and -Q7 - I haven't found a good answer so far, and was hoping this could be added to the documentation?

My goal is to achieve maximum sensitivity when mapping proteins againt a full genome (mammalian-sized) - and I am happy to sacrifice speed if this helps increase the "hit" rate. But randomly changing values does not seem like a good strategy if I don't know what they do. Maybe there is a very short explanation to help guide me?

Cheers,
Marc

**Comment by ogotoh** [comment]
-Q_N_ option:
_N_=0,4: DP procedure without HSP search. Considerably slow
_N_=1,2,3,5,6,7: Recursive HSP search up to the level of (_N_ % 4)

Like other common heuristic sequence similarity search algorithms, such as Blast, Fasta, and PatternHunter, Spaln involves fast HSP (high scoring pair) search phase. Usually, such algorithms first find continuous or discontinuous _k_-mer words of alphabet size a common to the query and the target sequences. Note that the alphabet size is fixed to 4 for DNA vs DNA searches but a ‘reduced alphabet’ can be used for Protein vs DNA or Protein vs Protein searches. As the _k_-mer and alphabet sizes are the larger, the search is the faster and more specific but less sensitive. Spaln first tries a set of large _k_-mer and alphabet sizes. If the search is successful, Spaln proceeds to the next phase, but otherwise progressively smaller _k_-mer and/or alphabet sizes are examined. _N_ % 4 specifies how many times this procedure is repeated. The default values for the sets of _k_-mer and alphabet sizes are preset within the program, but you can change individual values by command-line options.

It is a subtle problem to choose the best _N_ in combination with the -yX option, which depends on many factors. You may think that the full DP would be most accurate. It is generally true but not always so. I recommend first to use -Q3 or -Q7 option together with -yX1 (default).  You may also try ‘cross-species’ option -yX2, if the query and the genomic sequences are expected to be remotely related.

Although it is not within the scope of the current version of Spaln, you might increase the mapping phase sensitivity by formatting the genomic sequence with -XC3 or -XC4 option (multiple seed patterns at the block search phase). Although I implemented this option many years ago, I haven’t extensively examined its effectiveness as yet.

Osamu,
