### ISSUE TITLE
Database not found. Specify database! error

### ISSUE THREAD

**Issue by mickey-spongebob** [ogotoh/spaln#45]
Hi Ogotoh,

Hope this finds you well. Thank you for the tool and I'm looking forward to trying it out :-) 

I'm having troubles however with the error:

"/home/spaln/src/../seqdb/bflgnm not found. Specify database!", where 'bflgnm' is the _Branchiostoma floridae_ genome and would like to align proteins to the genome. 

Random question, I assume .mfa is essentially an .fa file, except it has multiple sequences in the same file. Unless I severely misunderstood the difference?

Installation went smoothly thanks to the detailed instructions :-).  

Firstly, I downloaded a multi-fasta file containing all the chromosome sequences into the _seqdb_ directory. I then executed 'spaln -W -KD -XG2M bflgnm.mfa'. This ran fine and gave me all the .idx, .grp, .odr, .seq, .ent and .bkn files. However, when I ran 'spaln -Q4 -O0 -Dbflgnm bfl.pep', where bfl.pep is the multi-protein sequence file that I'd like to align to the genome, it returns the error below:
 
"/home/spaln/src/../seqdb/bflgnm not found. Specify database!"

I also tried following the instructions using makeidx.pl and this runs without any errors, but this command 'spaln -W -KD -XG2M bflgnm.mfa' still fails to run successfully. 

My purpose of using the tool is to align proteins to my genome of interest, and generate a gff3 file. This was the tool I came across and thought to give it a try. Please let me know if this is not possible with this tool.

Any advice would be greatly appreciated, ad I apologise in advance if I've overlooked an important detail.

Thank you in advance and wishing you well,
kevin

**Comment by ogotoh** [comment]
Hi Ogotoh,

Hope this finds you well. Thank you for the tool and I'm looking forward to trying it out :-)

I'm having troubles however with the error:

"/home/spaln/src/../seqdb/bflgnm not found. Specify database!", where 'bflgnm' is the Branchiostoma floridae genome and would like to align proteins to the genome.

Random question, I assume .mfa is essentially an .fa file, except it has multiple sequences in the same file. Unless I severely misunderstood the difference?

Installation went smoothly thanks to the detailed instructions :-).

Firstly, I downloaded a multi-fasta file containing all the chromosome sequences into the seqdb directory. I then executed 'spaln -W -KD -XG2M bflgnm.mfa'. This ran fine and gave me all the .idx, .grp, .odr, .seq, .ent and .bkn files. However, when I ran 'spaln -Q4 -O0 -Dbflgnm bfl.pep', where bfl.pep is the multi-protein sequence file that I'd like to align to the genome, it returns the error below:

"/home/spaln/src/../seqdb/bflgnm not found. Specify database!"

I also tried following the instructions using makeidx.pl and this runs without any errors, but this command 'spaln -W -KD -XG2M bflgnm.mfa' still fails to run successfully.

My purpose of using the tool is to align proteins to my genome of interest, and generate a gff3 file. This was the tool I came across and thought to give it a try. Please let me know if this is not possible with this tool.

Any advice would be greatly appreciated, and I apologise in advance if I've overlooked an important detail.

Thank you in advance and wishing you well,
kevin
 
Dear Kevin,

Yes, the input genomic sequence file must be in the ordinary FASTA format allowing for multiple entries. The extension must be .mfa or .gf if you use makeidx.pl. However, this restriction is unnecessary if you use spaln -W.

For amino acid queries, the genomic sequence must be formatted with -KP instead of -KD option. 
$ spaln -W -KP -XG2M bflgnm.mfa	or
$ makeidx.pl -ip -XG2M bflgnm.mfa


Spaln tries to find formatted files in the directories in the following order:
1)	Current directory.
2)	The directory specified at the compile time (./configure –help). By default, this directory is ../seqdb relative to the directory where you ran ./configure. I wonder if your seqdb/ might differ from this default directory, (in your case, /home/spaln/seqdb/). Thus, the simplest solution to your trouble would be to move your seqdb/ to the default location.
3)	The directory specified by the env variable ALN_DBS. With bash, you may set it by the command: $ export ALN_DBS=/full_path_to_your_seqdb.

Osamu,

**Comment by mickey-spongebob** [comment]
Hi Osamu,

Thank you so much! It now works :-) I'll close the issue.

Apologies for the trivial issue raised. Wishing you and your loved ones well.

Thank you again,

best,
kevin
